### ISSUE TITLE
Make the testing fake recipe idempotent

### ISSUE THREAD

**Issue by douglaswth** [rightscale-cookbooks/ephemeral_lvm#14]
Something like:

```ruby
execute 'dd if=/dev/zero of=/vfile0 bs=1024 count=65536' do
  creates '/vfile0'
end

execute 'losetup /dev/loop0 /vfile0' do
  not_if 'losetup -j /vfile0 | grep /dev/loop0'
end
```

With the loop over multiple devices, of course.

**Comment by rshade** [comment]
are you looking to remove the helper library

**Comment by douglaswth** [comment]
@rshade It looks like Lopaka already fixed this a while back in the helper library; you guys are the maintainers of this now so it's up to you!

**Comment by rshade** [comment]
@douglaswth thank you sir, closing then .
