### ISSUE TITLE
misleading error message when EC2 node doesn't have ephemeral block devices

### ISSUE THREAD

**Issue by juliandunn** [rightscale-cookbooks/ephemeral_lvm#2]
Some EC2 instances don't have ephemeral block devices assigned at all, so there is no key node['ec2']['block_device_mapping_ephemeral']. Thus, this error message is misleading when the "else" code path is reached:

https://github.com/rightscale-cookbooks/ephemeral_lvm/blob/master/libraries/helper.rb#L73

**Comment by rshade** [comment]
@juliandunn Is this still a problem?

**Comment by juliandunn** [comment]
Nah it's cool, I figured it out. Even though these instances have ephemeral devices assigned by default you still have to ask EC2 to attach them. I started up an m3.medium today and the cookbook works as expected. Thanks!

**Comment by rshade** [comment]
Thank you for validating.
