### ISSUE TITLE
Should allow to mount with different options

### ISSUE THREAD

**Issue by chrisduong** [rightscale-cookbooks/ephemeral_lvm#31]
Hi,

I wanted to mount LVM with `defaults,noauto,noatime` for better performance (I think `noatime` is faster for SSD) but those options cannot be modified in your **LWRP** lvm_logical_volume.

```ruby
lvm_volume_group node['ephemeral_lvm']['volume_group_name'] do
      physical_volumes ephemeral_devices

      logical_volume node['ephemeral_lvm']['logical_volume_name'] do
        size node['ephemeral_lvm']['logical_volume_size']
        filesystem node['ephemeral_lvm']['filesystem']
        mount_point location: node['ephemeral_lvm']['mount_point'], options: ['defaults', 'noauto'], pass: 0
        if ephemeral_devices.size > 1
          stripes ephemeral_devices.size
          stripe_size node['ephemeral_lvm']['stripe_size'].to_i
        end
      end
    end
```
Could you extend your resource with a new attribute like  `mount_options`.
Thanks

**Comment by jhauf-nativex** [comment]
I would like to second this request. We have an application that cannot use the 'noauto' option. It would be nice if we had an attribute like mount_options to specify the options for ourselves.

**Comment by jhauf-nativex** [comment]
Here is a pull request that should resolve this issue: https://github.com/rightscale-cookbooks/ephemeral_lvm/pull/34

**Comment by lopaka** [comment]
Hello everyone,

First off, we appreciate people using and contributing to our cookbooks - thanks!

There is already a pull request which handles this issue: #25 

Development and testing of our cookbooks will commence in the very near future, at which time we can validate and merge pull request #25   So, stay tuned!

Thanks,
Lopaka
