### ISSUE TITLE
Default recipe is broken and fails during compilation

### ISSUE THREAD

**Issue by drywheat** [rightscale-cookbooks/ephemeral_lvm#32]
In v1.0.9 and above, the default recipe uses a `Mixlib::Shellout` call to `vgs` and fails to compile if the system has a minimal build which doesn't already include the lvm package (see [here](https://github.com/rightscale-cookbooks/ephemeral_lvm/blob/a28d7802f85d842db5d7e2aab406c774090dd304/recipes/default.rb#L43)).

This recipe has been written to install the correct lvm package, but that does not occur until the 2nd phase of the chef run (convergence). The offending line should be rewritten to address this issue, perhaps using a `ruby_block` resource.

**Comment by rshade** [comment]
Can you test with the latest rev?
