### ISSUE TITLE
Rightscale fails to import v1.0.13 version

### ISSUE THREAD

**Issue by areznikov-kabam** [rightscale-cookbooks/ephemeral_lvm#41]
Hello.

Rightscale fails to import v1.0.13 version with the following error

Metadata for "ephemeral_lvm" declares an attribute "ephemeral_lvm/mount_point_properties" that has a 'default' field that does not match 'type' field "string"
Failed to update cookbook 'ephemeral_lvm' (1.0.13)
Failed to update cookbook repo: Validation failed: Raw metadata Metadata for "ephemeral_lvm" declares an attribute "ephemeral_lvm/mount_point_properties" that has a 'default' field that does not match 'type' field "string"

**Comment by areznikov-kabam** [comment]
thank you.
Confirm that issue is fixed in v1.0.15

**Comment by rshade** [comment]
Thank you for testing
